// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YazilimEnvanteri.Data;

#nullable disable

namespace YazilimEnvanteri.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260918110457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.BirimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltBirim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UstBirim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("YazilimUzmaniId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YazilimUzmaniId");

                    b.ToTable("Birimler", (string)null);
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.PersonelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SorumluPersonel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.ToTable("Personeller", (string)null);
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.ProjeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjeAciklamasi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ProjeAktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjeDurum")
                        .HasColumnType("integer");

                    b.Property<string>("ProjeHizmetAlani")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Projenin hizmet alanını belirtir. Örneğin: Yazılım, Altyapı, Uygulama vb.");

                    b.Property<int>("ProjeKodu")
                        .HasColumnType("integer");

                    b.Property<int>("ProjeKritiklik")
                        .HasColumnType("integer");

                    b.Property<string>("Sunucu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TeknolojiId")
                        .HasColumnType("integer");

                    b.Property<int>("YazilimUzmaniId")
                        .HasColumnType("integer");

                    b.Property<string>("websiteUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("ProjeKodu")
                        .IsUnique();

                    b.HasIndex("TeknolojiId");

                    b.HasIndex("YazilimUzmaniId");

                    b.ToTable("Proje", (string)null);
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.TeknolojiEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackendTeknoloji")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EntegrasyonDurum")
                        .HasColumnType("boolean");

                    b.Property<string>("FrontendTeknoloji")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Veritabani")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("eimzaDurum")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Teknolojiler", (string)null);
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.YazilimUzmaniEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Birim")
                        .HasColumnType("integer");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gorev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullanıcıAdi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComputedColumnSql("SUBSTRING(Email, 1, CHARINDEX('@', Email) - 1)", true);

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjeId")
                        .HasColumnType("integer");

                    b.Property<string>("SorumluFirma")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Birim");

                    b.HasIndex("Eposta");

                    b.HasIndex("KullanıcıAdi");

                    b.HasIndex("ProjeId");

                    b.ToTable("YazilimUzmanlari", (string)null);
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.BirimEntity", b =>
                {
                    b.HasOne("YazilimEnvanteri.Models.Entities.YazilimUzmaniEntity", null)
                        .WithMany()
                        .HasForeignKey("YazilimUzmaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.ProjeEntity", b =>
                {
                    b.HasOne("YazilimEnvanteri.Models.Entities.BirimEntity", null)
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YazilimEnvanteri.Models.Entities.TeknolojiEntity", null)
                        .WithMany()
                        .HasForeignKey("TeknolojiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YazilimEnvanteri.Models.Entities.YazilimUzmaniEntity", null)
                        .WithMany()
                        .HasForeignKey("YazilimUzmaniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("YazilimEnvanteri.Models.Entities.YazilimUzmaniEntity", b =>
                {
                    b.HasOne("YazilimEnvanteri.Models.Entities.BirimEntity", null)
                        .WithMany()
                        .HasForeignKey("Birim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YazilimEnvanteri.Models.Entities.ProjeEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
